# Generated by Django 4.1.1 on 2022-10-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=50)),
                ('cuerpo', models.TextField()),
                ('autor', models.CharField(max_length=150)),
                ('fecha', models.CharField(max_length=200)),
            ],
        ),
    ]
