# Generated by Django 4.1.1 on 2022-10-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicaciones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='blog_imagenes'),
        ),
    ]
