# Generated by Django 4.1.1 on 2022-10-10 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_publicaciones_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='usario',
            new_name='usuario',
        ),
    ]
